### PR TITLE
Add Offset as a new method to the Attachments struct

### PR DESCRIPTION
**Pull request by xplshn**

### CODE REVIEW

**Comment by maja42** [comment]
Please add a test case (a sub test in TestAttachments) for the new method, so I can merge it.
Since I'm currently abroad though, I might need a few days to merge.

**Comment by xplshn** [comment]
Added the corresponding test case :)

**Comment by xplshn** [comment]
Is this library abandonware now?

**Comment by maja42** [comment]
No it isn't. I came back from my vacation just yesterday and will need a few days to get up to date on my projects again.
Unfortunately I wasn't able to verify the changes/merge the PR in a way I was comfortable with while abroad.

**Comment by maja42** [comment]
Now included in v1.3.0

**Pull request merged**
